name: opportunity-tracker
services:
  db:
    image: postgres:17
    container_name: tracker-db
    restart: always
    env_file:
      - .env.prod
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PWD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    container_name: tracker-redis
    restart: always
    env_file:
      - .env.prod
    ports:
      - "6379:6379"

  celery:
    build: . #docker.io/hirensoni913/opp_tracker_main:latest
    container_name: celery-worker
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env.prod
    command: celery -A opportunity_tracker worker --loglevel=info
  web:
    build: . #docker.io/hirensoni913/opp_tracker_main:latest
    container_name: web-app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.prod
    environment:
      DEBUG: 0
      DATABASE_ENGINE: ${DB_ENGINE}
      DATABASE_NAME: ${DB_NAME}
      DATABASE_USERNAME: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PWD}
      DATABASE_HOST: ${DB_HOST}
      DATABASE_PORT: ${DB_PORT}
    volumes:
      - media:/app/opportunity_tracker/media
volumes:
  postgres_data:
  media:
