# Generated by Django 5.1.2 on 2025-11-18 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_opportunitysubscription_preferred_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunitysubscription',
            options={'ordering': ['user__first_name', 'user__last_name', 'opportunity__ref_no']},
        ),
    ]
