# Generated by Django 5.1.2 on 2025-04-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20250303_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['code'], 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='fundingagency',
            options={'ordering': ['name'], 'verbose_name_plural': 'Funding Agencies'},
        ),
        migrations.AlterModelOptions(
            name='opportunity',
            options={'verbose_name_plural': 'Opportunities'},
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='clarification_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='intent_bid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
