# Generated by Django 5.1.2 on 2025-06-03 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_client_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred', to='tracker.opportunity'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='status',
            field=models.IntegerField(choices=[(1, 'Entered'), (2, 'Go'), (3, 'NO-Go'), (4, 'Consider'), (5, 'Submitted'), (6, 'Lost'), (7, 'Won'), (8, 'Cancelled'), (9, 'Assumed Lost'), (10, 'N/A'), (11, 'Transfer to RFP')], default=1),
        ),
    ]
