# Generated by Django 5.1.2 on 2025-09-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_opportunity_parent_alter_opportunity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='submission_validity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
