# Generated by Django 5.1.2 on 2025-11-04 14:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_opportunity_submission_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='partners',
            field=models.ManyToManyField(blank=True, null=True, related_name='partner_Opportunities', to='tracker.institute'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='submission_validity',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(365)]),
        ),
    ]
