# Generated by Django 5.1.2 on 2025-11-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_opportunity_result_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='is_noncompetitive',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
