# Generated by Django 5.1.2 on 2025-11-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_opportunity_is_noncompetitive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='is_noncompetitive',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
