name: Docker Image Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: |
        docker build -t docker.io/${{ github.actor }}/opp_tracker_main:latest .
   
    - name: Push Docker image to Docker Hub
      run: |
        docker push docker.io/${{ github.actor }}/opp_tracker_main:latest
      
