name: Docker Image Main

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and tag Docker image
      run: |
        set -e  # Stop on error
        IMAGE_NAME=docker.io/${{ secrets.DOCKER_USERNAME }}/opp_tracker_main:latest
        docker build --no-cache -t $IMAGE_NAME .

    - name: Push Docker image to Docker Hub
      run: |
        set -e
        IMAGE_NAME=docker.io/${{ secrets.DOCKER_USERNAME }}/opp_tracker_main:latest
        docker push $IMAGE_NAME

    - name: Log out from Docker Hub
      run: docker logout
